In [12]:
survival_data = pd.DataFrame({
    "patient_id": ["P001", "P002", "P003"],
    "rfs_days": [800, 250, 1200],
    "event": [0, 1, 0]
})

survival_data

  patient_id  rfs_days  event
0       P001       800      0
1       P002       250      1
2       P003      1200      0

In [1]:
patient_id = "P001"
age = 63
hpv_positive = True
tumour_volume = 24.7

print(patient_id)
print(age)
print(hpv_positive)
print(tumour_volume)

P001
63
True
24.7

In [2]:
print(type(patient_id))
print(type(age))
print(type(hpv_positive))
print(type(tumour_volume))

<class 'str'>
<class 'int'>
<class 'bool'>
<class 'float'>

In [3]:
ages = [63, 55, 71, 49]

print(ages)
print(ages[0])
print(ages[1])

[63, 55, 71, 49]
63
55

In [4]:
for age in ages:
    print(age)

63
55
71
49

In [5]:
age = 63

if age >= 60:
    print("Age is 60 or above")
else:
    print("Age is below 60")

Age is 60 or above

In [6]:
def classify_age(age):
    if age >= 60:
        return "60 or older"
    else:
        return "Below 60"

result = classify_age(63)
print(result)

60 or older

In [7]:
import numpy as np

ages_array = np.array([63, 55, 71, 49])

print(ages_array)
print("Mean age:", ages_array.mean())

[63 55 71 49]
Mean age: 59.5

In [8]:
import pandas as pd

data = {
    "patient_id": ["P001", "P002", "P003"],
    "age": [63, 55, 71],
    "hpv": ["positive", "negative", "positive"]
}

patients = pd.DataFrame(data)

patients

  patient_id  age       hpv
0       P001   63  positive
1       P002   55  negative
2       P003   71  positive

In [9]:
print(patients.shape)
print(patients.columns)
print(patients["age"].mean())

(3, 3)
Index(['patient_id', 'age', 'hpv'], dtype='str')
63.0

In [10]:
older_patients = patients[patients["age"] > 60]

older_patients

  patient_id  age       hpv
0       P001   63  positive
2       P003   71  positive

In [11]:
# 1. Filter patients older than 60
older_patients = patients[patients["age"] > 60]
print(older_patients)

# 2. Add survival-style columns
patients["rfs_days"] = [800, 250, 1200]
patients["event"] = [0, 1, 0]

print(patients)

# 3. Count observed events
print("Number of events:", patients["event"].sum())

# 4. Average age
print("Mean age:", patients["age"].mean())

  patient_id  age       hpv
0       P001   63  positive
2       P003   71  positive
  patient_id  age       hpv  rfs_days  event
0       P001   63  positive       800      0
1       P002   55  negative       250      1
2       P003   71  positive      1200      0
Number of events: 1
Mean age: 63.0